### ISSUE TITLE
Does Aloja support LLAP ?   

### ISSUE THREAD

**Issue by nakhanha** [Aloja/aloja#38]

**Comment by npoggi** [comment]
Not by itself, it was not added the extra hive configuration.  But if benchmarking a system that has it already installed ie., PaaS Hadoop, then yes.

**Comment by nakhanha** [comment]
HI Nico,

So you are saying if my cluster has hiveserver2 it should work ?

Thanks,
Nasrulla

**Comment by npoggi** [comment]
@nakhanha  if your cluster already has Hive + LLAP setup, then yes.
